{
 "title": "Assisted Service Resource Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "ocm_gateway_name",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq{namespace=~\"uhc.*\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods Resource Utilization/Requests",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"assisted-service\"}[5m])) / max(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"assisted-service\", resource=\"cpu\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"assisted-service-.*\",container=\"assisted-service\"}) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"assisted-service-.*\",container=\"assisted-service\",resource=\"memory\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Pods Resource Utilization/Limits",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"assisted-service\"}[5m])) / max(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"assisted-service\", resource=\"cpu\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"assisted-service-.*\", container=\"assisted-service\"}) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\"assisted-service-.*\",resource=\"memory\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Pods Network Received ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"assisted-service-.*\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Pods Network Transmited ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"assisted-service-.*\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Pods CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total {namespace=\"$namespace\",pod=~\"assisted-service-.*\"\n} [5m])) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"assisted-service\", resource=\"cpu\"}) by (container)",
     "legendFormat": "Requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"assisted-service\", resource=\"cpu\"}) by (container)",
     "legendFormat": "Limits"
    },
    {
     "expr": "avg(rate( container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\",pod=~\"assisted-service-.*\"\n} [5m]))",
     "legendFormat": "Average throttled"
    }
   ]
  },
  {
   "title": "CPU vs response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total {namespace=\"$namespace\",pod=~\"assisted-service-.*\"\n} [5m]))",
     "legendFormat": "Average CPU usage"
    },
    {
     "expr": "avg(rate( container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\",pod=~\"assisted-service-.*\"\n} [5m]))",
     "legendFormat": "Average Throttled"
    },
    {
     "expr": "histogram_quantile(.99, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "Pods Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=~\"assisted-service-.*\", container=\"assisted-service\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"assisted-service-.*\", container=\"assisted-service\", resource=\"memory\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"assisted-service-.*\", container=\"assisted-service\", resource=\"memory\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"assisted-service-.*\", container=\"assisted-service\"}) by (pod)",
     "legendFormat": "Memory usage {{pod}}"
    }
   ]
  },
  {
   "title": "Pods Network Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"assisted-service-.*\"}[5m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\"assisted-service-.*\"}[5m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "5XX errors",
   "type": "timeseries",
   "description": "5XX errors from OCM gateway to Assisted Installer Service, passing through Openshift Router",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{namespace=\"$namespace\",code=~\"5..\"}[10m])) by (code)",
     "legendFormat": "Assisted Installer {{ code }}"
    },
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq{namespace=\"$ocm_gateway_name\",envoy_cluster_name=\"assisted-install\",envoy_response_code=~\"5..\"}[10m])) by (envoy_response_code)",
     "legendFormat": "OCM Gateway {{envoy_response_code}}"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry{namespace=\"$ocm_gateway_name\",envoy_cluster_name=\"assisted-install\"}[10m])) * 600",
     "legendFormat": "OCM Gateway Retries"
    },
    {
     "expr": "sum(rate(haproxy_server_http_responses_total{route=\"assisted-service\",code=\"5xx\"}[10m])) * 600",
     "legendFormat": "Openshift Router 5XX"
    }
   ]
  }
 ]
}