{
 "title": "Assisted Installer Logs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "error_level", "label": "Error level", "query": "error,warning,info,.*" },
   { "name": "logs_query", "label": "Query", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Production logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Production Logs - Tail",
   "type": "logs",
   "description": "Last lines for Assisted Installer Service Production logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expression": "fields message\n| filter kubernetes.container_name = \"assisted-service\" and kubernetes.namespace_name = \"assisted-installer-production\"\n| sort @timestamp desc\n| limit 300",
     "logGroupNames": [
      "app-sre-prod-04.assisted-installer-production"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Image Service Logs - Tail",
   "type": "logs",
   "description": "Last lines for Assisted Image Service Production logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expression": "fields message\n| filter kubernetes.container_name = \"assisted-image-service\" and kubernetes.namespace_name = \"assisted-installer-production\"\n| sort @timestamp desc\n| limit 300 ",
     "logGroupNames": [
      "app-sre-prod-04.assisted-installer-production"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Production Logs - Warning",
   "type": "logs",
   "description": "Assisted Installer Service Production warning logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expression": "fields message\n| filter kubernetes.container_name = \"assisted-service\" and kubernetes.namespace_name = \"assisted-installer-production\"\n| filter message LIKE 'level=warning'\n| sort @timestamp desc\n| limit 300",
     "logGroupNames": [
      "app-sre-prod-04.assisted-installer-production"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Production Logs - Error",
   "type": "logs",
   "description": "Assisted Installer Service Production error logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expression": "fields message\n| filter kubernetes.container_name = \"assisted-service\" and kubernetes.namespace_name = \"assisted-installer-production\"\n| filter message LIKE 'level=error'\n| sort @timestamp desc\n| limit 300",
     "logGroupNames": [
      "app-sre-prod-04.assisted-installer-production"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  { "title": "Stage logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Stage Logs",
   "type": "logs",
   "description": "Assisted Installer Service Stage, dynamic error level",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{kubernetes_namespace_name=\"assisted-installer-stage\", kubernetes_container_name=\"assisted-service\"} |~ \"$logs_query\" | json | line_format \"{{.message}}\" | pattern `<_> level=<level> msg=\"<msg>\" <_>` | level =~ \"$error_level\" | line_format \"{{.msg}}\"",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}