{
 "title": "Assisted Installer Kafka",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aws_kafka_global_topic_count_maximum{cluster_name=~\"assisted-installer.*\"}) by (cluster_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aws_kafka_partition_count_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offset lag",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aws_kafka_max_offset_lag_maximum{cluster_name=~\"assisted-installer.*\",consumer_group!~\"^amazon.*\"}) by (consumer_group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Offset Lag time",
   "type": "stat",
   "description": "Time estimate (in seconds) to drain MaxOffsetLag.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aws_kafka_estimated_max_time_lag_maximum{cluster_name=~\"assisted-installer.*\",consumer_group!~\"^amazon.*$\"}) by (consumer_group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage after GC",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aws_kafka_heap_memory_after_gc_maximum{cluster_name=~\"assisted-installer.*\"}) by (broker_id)",
     "legendFormat": "broker {{broker_id}}"
    }
   ]
  },
  {
   "title": "CPU Credits",
   "type": "stat",
   "description": "Broker with least credits",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aws_kafka_cpucredit_balance_minimum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions under min Isr",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aws_kafka_under_min_isr_partition_count_maximum{cluster_name=~\"assisted-installer.*\"}) by (broker_id)",
     "legendFormat": "broker {{broker_id}}"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aws_kafka_under_replicated_partitions_maximum{cluster_name=~\"assisted-installer.*\"}) by (broker_id)",
     "legendFormat": "broker {{broker_id}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Session state",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(aws_kafka_zoo_keeper_session_state_minimum{cluster_name=~\"assisted-installer.*\"}) by (broker_id)",
     "legendFormat": "Broker {{broker_id}}"
    }
   ]
  },
  {
   "title": "Average maximum CPU usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(aws_kafka_cpu_user_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Messages rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rate" } },
   "targets": [
    {
     "expr": "aws_kafka_messages_in_per_sec_maximum{cluster_name=~\"assisted-installer.*\"}",
     "legendFormat": "message rate broker {{broker_id}}"
    }
   ]
  },
  {
   "title": "Offset lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max(aws_kafka_max_offset_lag_maximum{cluster_name=~\"assisted-installer.*\",consumer_group=~\"enriched.*\"}) by (consumer_group)",
     "legendFormat": "offset lag {{consumer_group}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Bytes In/Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(aws_kafka_bytes_in_per_sec_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "bytes in"
    },
    {
     "expr": "- sum(aws_kafka_bytes_out_per_sec_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "bytes out"
    }
   ]
  },
  {
   "title": "ZooKeeper latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(aws_kafka_zoo_keeper_request_latency_ms_mean_maximum{cluster_name=~\"assisted-installer.*\"}) by (broker_id)",
     "legendFormat": "ZooKeeper latency broker {{broker_id}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU usage overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "avg(aws_kafka_cpu_idle_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "idle avg"
    },
    {
     "expr": "avg(aws_kafka_cpu_user_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "user avg"
    },
    {
     "expr": "avg(aws_kafka_cpu_system_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "system avg"
    },
    {
     "expr": "avg(aws_kafka_cpu_io_wait_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "iowait avg"
    }
   ]
  },
  {
   "title": "Memory usage overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(aws_kafka_memory_used_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "memory usage avg"
    },
    {
     "expr": "stddev(aws_kafka_memory_used_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "memory usage stddev"
    },
    {
     "expr": "avg(aws_kafka_memory_buffered_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "buffered memory avg"
    },
    {
     "expr": "stddev(aws_kafka_memory_buffered_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "buffered memory stddev"
    },
    {
     "expr": "avg(aws_kafka_memory_free_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "free memory avg"
    },
    {
     "expr": "avg(aws_kafka_memory_cached_maximum{cluster_name=~\"assisted-installer.*\"})",
     "legendFormat": "cached memory"
    },
    { "expr": "aws_kafka_memory", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Broker CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_kafka_cpu_user_maximum{cluster_name=~\"assisted-installer.*\"}",
     "legendFormat": "user (broker {{broker_id}})"
    },
    {
     "expr": "aws_kafka_cpu_system_maximum{cluster_name=~\"assisted-installer.*\"}",
     "legendFormat": "system (broker {{broker_id}})"
    },
    {
     "expr": "aws_kafka_cpu_idle_minimum{cluster_name=~\"assisted-installer.*\"}",
     "legendFormat": "idle (broker {{broker_id}})"
    }
   ]
  },
  {
   "title": "Broker Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_kafka_memory_used_maximum{cluster_name=~\"assisted-installer.*\"}",
     "legendFormat": "memory usage broker {{broker_id}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(aws_kafka_kafka_data_logs_disk_used_maximum{cluster_name=~\"assisted-installer.*\"}) by (broker_id)",
     "legendFormat": "logs disk used (broker {{broker_id}})"
    },
    {
     "expr": "max(aws_kafka_root_disk_used_maximum{cluster_name=~\"assisted-installer.*\"}) by (broker_id)",
     "legendFormat": "root disk used (broker {{broker_id}})"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "max(aws_kafka_swap_free_maximum{cluster_name=~\"assisted-installer.*\"}) by (broker_id)",
     "legendFormat": "swap free broker {{broker_id}}"
    },
    {
     "expr": "max(aws_kafka_swap_used_maximum{cluster_name=~\"assisted-installer.*\"}) by (broker_id)",
     "legendFormat": "swap used broker {{broker_id}}"
    }
   ]
  },
  {
   "title": "CPU Credit Balance evolution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "min(aws_kafka_cpucredit_balance_minimum{cluster_name=~\"assisted-installer.*\"}) by (cluster_name, broker_id)",
     "legendFormat": "credits broker {{broker_id}}"
    }
   ]
  }
 ]
}