{
 "title": "Notifications Projection",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "kafka_prometheus", "query": "prometheus" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "environment", "query": "integration,stage,production" }
  ]
 },
 "panels": [
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bytes in/out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_topic:kafka_server_brokertopicmetrics_bytes_in_total:rate5m{topic=\"events-stream-production\"})",
     "legendFormat": "Bytes in"
    },
    {
     "expr": "sum(kafka_topic:kafka_server_brokertopicmetrics_bytes_out_total:rate5m{topic=\"events-stream-production\"})",
     "legendFormat": "Bytes out"
    }
   ]
  },
  {
   "title": "Messages rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kafka_topic:kafka_server_brokertopicmetrics_messages_in_total:rate5m{job=\"assisted-installer-event-production\",topic=\"events-stream-production\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Projection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Consumergroup members",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consumergroup:kafka_consumergroup_members:count{job=\"assisted-installer-event-production\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"assisted-installer-production\",container=\"projection\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}